spring.application.name=redis-rate-limiter
server.port=8080

# Dynamic Connection with Fallback to Localhost
spring.data.redis.host=valkey-35430946-rate-limiter.h.aivencloud.com
spring.data.redis.port=23570
spring.data.redis.password=AVNS_qHdEtFbfh8iToerXATr

# ? SSL ENABLER FOR AIVEN CLOUD (Yeh fix karega handshake failure)
spring.data.redis.ssl.enabled=true

# Actuator Endpoints Exposure
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=rate-limiter-service