spring.application.name=redis-rate-limiter
server.port=8080
spring.redis.host=${SPRING_REDIS_HOST:127.0.0.1}
spring.redis.port=${SPRING_REDIS_PORT:6379}
# Web configuration to expose actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus
# Show detailed metrics format
management.metrics.tags.application=rate-limiter-service